<template>
  <div class="control-section">
    <div class="form-container">
      <label class="e-label" for="ps">Page Size :</label>
      <ejs-dropdownlist 
        id="ps" 
        v-model="formData.pageSize" 
        :dataSource="pageSizeOptions"
        :fields="{ text: 'text', value: 'value' }"
        floatLabelType="Never"
      ></ejs-dropdownlist>

      <label class="e-label" for="po">Page Orientation :</label>
      <ejs-dropdownlist 
        id="po" 
        v-model="formData.pageOrientation" 
        :dataSource="orientationOptions"
        :fields="{ text: 'text', value: 'value' }"
        floatLabelType="Never"
      ></ejs-dropdownlist>

      <label class="e-label" for="pm">Page Margin :</label>
      <ejs-dropdownlist 
        id="pm" 
        v-model="formData.pageMargin" 
        :dataSource="marginOptions"
        :fields="{ text: 'text', value: 'value' }"
        floatLabelType="Never"
      ></ejs-dropdownlist>

      <label class="e-label" for="pr">Page Rotation :</label>
      <ejs-dropdownlist 
        id="pr" 
        v-model="formData.pageRotation" 
        :dataSource="rotationOptions"
        :fields="{ text: 'text', value: 'value' }"
        floatLabelType="Never"
      ></ejs-dropdownlist>

      <label class="e-label">Pages Count :</label>
      <div class="pages-inline">
        <ejs-textbox 
          id="pageCount" 
          v-model="formData.pageCount" 
          :readonly="true"
          cssClass="page-count-input"
        ></ejs-textbox>
        <ejs-button id="addPage" @click="addPage" :isPrimary="false">Add Page</ejs-button>
      </div>
    </div>
    <br />
    <br />
    <div>
      <p>
        Click the button to view a PDF document generated by JavaScript PDF Library. Please note that Adobe Reader or its
        equivalent is required to view the resultant document.
      </p>
    </div>
    <div class="actions">
      <ejs-button id="normalbtn" @click="createPdf" :isPrimary="true">Generate PDF</ejs-button>
    </div>
    <div id="action-description">
      <p>
        This sample demonstrates adding pages with different settings such as rotation, orientation and page size.
      </p>
    </div>
    <div id="description">
      <p>It is also possible to add or insert pages and sections, remove pages, rearrange pages, and more. More information about the pages and sections can be found in this documentation <a href="https://help.syncfusion.com/document-processing/pdf/pdf-library/javascript/pdf-pages">section</a>.</p>  
    </div>
  </div>
</template>
<style scoped>
  .control-section {
    max-width: none;
  }
  .control-section p {
    margin-bottom: 16px;
  }
  .form-container {
    display: grid;
    grid-template-columns: 180px auto;
    column-gap: 12px;
    row-gap: 20px;
    align-items: center;
  }
  .form-label {
    text-align: left;
    white-space: nowrap;
  }
  .form-container ::v-deep(.e-dropdownlist),
  .form-container ::v-deep(.e-input-group) {
    width: 220px !important;
  }
  .pages-inline {
    display: flex;
    gap: 8px;
    align-items: center;
  }
  .pages-inline ::v-deep(.page-count-input) {
    width: 100px;
    text-align: center;
  }
  .actions {
    margin-top: 16px;
  }
</style>
<script lang="ts">
import { defineComponent, reactive } from 'vue';
import { TextBoxComponent } from '@syncfusion/ej2-vue-inputs';
import { DropDownListComponent } from '@syncfusion/ej2-vue-dropdowns';
import { ButtonComponent } from '@syncfusion/ej2-vue-buttons';
import {
  PdfDocument,
  PdfPageSettings,
  PdfMargins,
  PdfPen,
  PdfBrush,
  PdfFontFamily,
  PdfFontStyle,
  PdfPageOrientation,
  PdfRotationAngle
} from '@syncfusion/ej2-pdf';

export default defineComponent({
  name: 'PageSettingsPdf',
  components: {
    'ejs-textbox': TextBoxComponent,
    'ejs-dropdownlist': DropDownListComponent,
    'ejs-button': ButtonComponent
  },
  setup() {
    const formData = reactive({
      pageSize: 'A4',
      pageOrientation: 'Portrait',
      pageMargin: 'No margin',
      pageRotation: '0',
      pageCount: '1'
    });

    const pageSizeOptions = [
      { text: 'Letter', value: 'Letter' },
      { text: 'Legal', value: 'Legal' },
      { text: 'A3', value: 'A3' },
      { text: 'A4', value: 'A4' },
      { text: 'A5', value: 'A5' },
      { text: 'B4', value: 'B4' },
      { text: 'B5', value: 'B5' }
    ];

    const orientationOptions = [
      { text: 'Portrait', value: 'Portrait' },
      { text: 'Landscape', value: 'Landscape' }
    ];

    const marginOptions = [
      { text: 'No margin', value: 'No margin' },
      { text: 'Small', value: 'Small' },
      { text: 'Large', value: 'Large' }
    ];

    const rotationOptions = [
      { text: '0', value: '0' },
      { text: '90', value: '90' },
      { text: '180', value: '180' },
      { text: '270', value: '270' }
    ];

    const addPage = () => {
      const current = parseInt(formData.pageCount || '1', 10);
      formData.pageCount = String(Math.max(1, current + 1));
    };

    const createPdf = (): void => {
      const ps = formData.pageSize;
      const po = formData.pageOrientation;
      const pm = formData.pageMargin;
      const pr = formData.pageRotation;
      const pageCount = parseInt(formData.pageCount || '1', 10);
      
      const settings = new PdfPageSettings();
      const size = getPageSize(ps);
      settings.size = size as any;
      settings.orientation = po === 'Portrait' ? PdfPageOrientation.portrait : PdfPageOrientation.landscape;
      settings.rotation = getRotationAngle(String(pr));
      settings.margins = new PdfMargins(getMargin(pm));

      const pdf = new PdfDocument();
      const pen = new PdfPen({ r: 0, g: 0, b: 0 }, 6);
      const lightGreenBrush = new PdfBrush({ r: 144, g: 238, b: 144 });
      const textBrush = new PdfBrush({ r: 0, g: 0, b: 0 });
      const footerFont = pdf.embedFont(PdfFontFamily.helvetica, 16, PdfFontStyle.regular);

      for (let i = 0; i < pageCount; i++) {
        const page = pdf.addPage(settings);
        const g = page.graphics;
        const client = g.clientSize;
        g.drawRectangle({ x: 0, y: 0, width: client.width, height: client.height }, lightGreenBrush);
        g.drawLine(pen, { x: 0, y: 100 }, { x: Math.min(300, client.width), y: 100 });
        const footerText = `Page ${i + 1} of ${pageCount}`;
        g.drawString(footerText, footerFont, { x: client.width - 150, y: client.height - 40, width: 140, height: 30 }, textBrush);
      }

      pdf.save('PageSettings.pdf');
      pdf.destroy();
    };

    const getPageSize = (name: string) => {
      const PAGE_SIZES: Record<string, { width: number; height: number }> = {
        Letter: { width: 612, height: 792 },
        Legal: { width: 612, height: 1008 },
        A3: { width: 842, height: 1191 },
        A4: { width: 595, height: 842 },
        A5: { width: 420, height: 595 },
        B4: { width: 729, height: 1032 },
        B5: { width: 516, height: 729 }
      };
      const key = (name || '').trim();
      return PAGE_SIZES[key] ?? PAGE_SIZES.A4;
    };

    const getMargin = (name: string): number => {
      const key = (name || '').trim();
      if (key === 'Small') return 20;
      if (key === 'Large') return 40;
      return 0;
    };

    const getRotationAngle = (deg: string): PdfRotationAngle => {
      switch ((deg || '').trim()) {
        case '90':
          return PdfRotationAngle.angle90;
        case '180':
          return PdfRotationAngle.angle180;
        case '270':
          return PdfRotationAngle.angle270;
        default:
          return PdfRotationAngle.angle0;
      }
    };

    return {
      formData,
      pageSizeOptions,
      orientationOptions,
      marginOptions,
      rotationOptions,
      addPage,
      createPdf
    };
  }
});
</script>