<template>
	<div>
		<!-- Component UI: single button to generate the sample PDF. -->
		<!-- The action-description and description blocks explain the sample. -->
		<div class="control-section">
			<div class="tablediv" style="font-size:14px">
				<text class="rowdiv">
					Click the button to view a PDF document generated by JavaScript PDF Library. Please note that Adobe Reader
					or its equivalent is required to view the resultant document.
				</text>

				<div class="tablediv" style="font-size:14px">
					<div class="rowdiv">
						<div class="celldiv">
							<table style="width:100%">
								<tr>
									<td align="left">
										<br />
										<!-- The Button component is initialized in the script's onMounted hook. -->
										<input type="submit" id="textFlow" class="e-btn" value="Generate PDF" style="width: 150px; text-transform:capitalize" />
									</td>
								</tr>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div id="action-description" style="margin-top: 10px">
			<p>
				This sample demonstrates the creation of PDF document with large text that flows over multiple pages. The user
				can also draw multiple paragraphs sequentially.
			</p>
		</div>

		<div id="description" style="margin-top: 10px">
			<p>
				This feature automatically layouts and draws the text in the specified bounds. When the text overflows a new
				page is created automatically and drawn in new page. More information about text flow can be found in this
				documentation <a
					href="https://help.syncfusion.com/document-processing/pdf/pdf-library/javascript/text">section</a>.
			</p>
		</div>
	</div>
</template>

<style scoped>
	.control-section {}
</style>

<script lang="ts">
import { defineComponent, onMounted } from 'vue';
import { Button } from '@syncfusion/ej2-buttons';
import {
	PdfDocument,
	PdfPage,
	PdfFontFamily,
	PdfLayoutFormat,
	PdfLayoutType,
	PdfLayoutBreakType,
	PdfBrush,
	PdfStandardFont,
	PdfTextElement
} from '@syncfusion/ej2-pdf';

export default defineComponent({
	name: 'TextFlowPdf',
	setup() {
		// Initialize UI and wire up the Generate PDF button after mount.
		// We use Syncfusion's `Button` to match the sample style.
		onMounted(() => {
			const button = new Button({}, '#textFlow');
			// Click handler triggers PDF generation logic below.
			button.element.onclick = generatePdf;
			// Expose function on window for consistency with original samples.
			(window as any).generatePdf = generatePdf;
		});
		async function generatePdf(): Promise<void> {
			// Load large sample text from CDN (optional). If it fails, textContent remains empty.
			let textContent = '';
			try {
				const resp = await fetch('https://cdn.syncfusion.com/content/pdf-resources/pdf-textFlow.txt');
				if (resp.ok) textContent = await resp.text();
			} catch (e) {
				// Network failure is non-fatal for the demo — proceed with empty content.
			}

			// Create PDF document and the first page.
			const doc: PdfDocument = new PdfDocument();
			const page: PdfPage = doc.addPage();
			const clientSize = page.graphics.clientSize;

			// Configure the layout so text will flow and paginate across pages automatically.
			const layoutFormat: PdfLayoutFormat = new PdfLayoutFormat();
			layoutFormat.layout = PdfLayoutType.paginate;
			layoutFormat.break = PdfLayoutBreakType.fitPage;
			layoutFormat.paginateBounds = { x: 0, y: 0, width: clientSize.width, height: clientSize.height };

			// Define a text element with styling and layout options
			const textElement: PdfTextElement = {
				text: textContent, // The text string to render
				font: new PdfStandardFont(PdfFontFamily.timesRoman as any, 14), // Times Roman font at 14pt
				brush: new PdfBrush({ r: 0, g: 0, b: 0 }), // Black color brush (RGB: 0,0,0)
				layoutFormat: layoutFormat // Apply the pagination layout settings
			} as any;

			// Draw the text element on the page within the specified bounds
			page.drawTextElement(textElement, {
				x: 0, // X coordinate starting position
				y: 0, // Y coordinate starting position
				width: clientSize.width, // Width matches page width
				height: clientSize.height // Height matches page height
			});

			// Save the file to the user's machine and release memory.
			doc.save('TextFlowOutput.pdf');
			// Destroy the document
			doc.destroy();
		}

		return {};
	}
});
</script>